### ISSUE TITLE
Auto run command with pm2 or anything

### ISSUE THREAD

**Issue by anhtuanng98** [binsentsu/am43-ctrl#11]
Thank you for your perfect code.

I have connect my AM43 to home assistant but when I close terminal, this connection will stop. I have try with pm2 which you suggest but this still happen or I have something wrong when config it Could you suggest some thing to run command in background and after reboot or guide me to config pm2 right?

My command:
`sudo am43ctrl xx:xx:xx:xx:xx:xx --url mqtt://192.168.xxx.xxx:xxxx -u mqtt -p passwd`

Thank you so much

**Comment by anhtuanng98** [comment]
I have done it :D thank you for your best codes

**Comment by reesion** [comment]
Hi,

I am having the exact issue where the connection will stop when i close the terminal. Are you able to advise what was your fix?

Thank you.

**Comment by anhtuanng98** [comment]
> Hi,
> 
> I am having the exact issue where the connection will stop when i close the terminal. Are you able to advise what was your fix?
> 
> Thank you.

[https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/](url)
You could try the first method :D

**Comment by reesion** [comment]
> [https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/](url)
> You could try the first method :D

Hi,

That didn't work for me as I am not using a PI. I ended up using crontab and that resolved the issue. Thanks for the help!
